### ISSUE TITLE
Add information of origin to MemoryLimiterWorker

### ISSUE THREAD

**Issue by posidron** [MozillaSecurity/ffpuppet#11]
At the moment there is no information about where or what triggered a [MEMORY_LIMIT_EXCEEDED](https://github.com/MozillaSecurity/ffpuppet/blob/master/workers/memory_limiter.py#L62) which makes filing reports for the IPC fuzzers not really possible for those cases.

Possible idea:

```
def get_gdb_stacktrace(pid):
  return subprocess.check_output(["gdb", "--batch", "-q", 
                                  "-ex", "thread apply all bt full", 
                                  "-ex", "quit", 
                                  "-p", "%d" % pid])
```

**Comment by tysmith** [comment]
Added in commit 8d43d82 & commit 3e2f738. Thanks for the suggestion.
