### ISSUE TITLE
Use auxCrashData for minidump data

### ISSUE THREAD

**Issue by choller** [MozillaSecurity/ffpuppet#16]
Right now (I think), the output of minidump_stackwalk is added to the log. This causes problems because this is all submitted as stderr to FuzzManager. Because we truncate stderr, some very long traces from minidump_stackwalk won't even fit into the log.

My suggestion would be to use the "auxCrashData" field when reporting this trace to FuzzManager. The field was specifically made for output of third-party tools (like GDB, minidump_stackwalk, etc) to include the crash data, rather than append it to stderr. It also makes viewing the raw crash data in FuzzManager a lot easier because you don't have to dig through stderr.

Thanks!

**Comment by tysmith** [comment]
Added as of commit 58810c0
