### ISSUE TITLE
Redirect to file: broken on windows.

### ISSUE THREAD

**Issue by jschwartzentruber** [MozillaSecurity/ffpuppet#18]
When launching ffpuppet on windows with -u, the redirect is broken:

    set DEBUG=1
    python -m ffpuppet \build\firefox.exe -u tc.html
    ...
    D ffpuppet [2017-09-07 14:46:21] sending response with redirect url: 'file://////C:/Users/user/Desktop/tc.html'

The browser doesn't resolve the file: url. Entering it manually as `file://C:/Users/...` works fine.

**Comment by tysmith** [comment]
Fixed by commit ab8fc75.
