### ISSUE TITLE
xvfb vs no xvfb

### ISSUE THREAD

**Issue by areuu** [MozillaSecurity/ffpuppet#185]
Hi, I just curious about when fuzz under xvfb mode and no xvfb mode, what's the different between that?

**Comment by tysmith** [comment]
[Xvfb](https://en.wikipedia.org/wiki/Xvfb) is used on headless systems to run the browser. `--headless` can also be used but some code may not be exercised.

Also when fuzzing [Grizzly](https://github.com/MozillaSecurity/grizzly) uses FFPuppet and adds at lot of extra functionality.
