### ISSUE TITLE
Don't raise when attempting to use xvfb on non-linux platforms

### ISSUE THREAD

**Issue by pyoor** [MozillaSecurity/ffpuppet#90]
We should probably warn instead of raising a fatal error here:
https://github.com/MozillaSecurity/ffpuppet/blob/a70efd043be281c64166ee44ba6fff0804a79d2d/ffpuppet/core.py#L122

**Comment by tysmith** [comment]
This is avoided by https://github.com/MozillaSecurity/grizzly/pull/220
